### ISSUE TITLE
Reduce indent of page display

### ISSUE THREAD

**Issue by CentralScrutinizer-moonbog** [MetroDCDSA/MetroDCDSA.github.io#10]
Pages feel a bit claustrophobic - need to consider increase page size for clearer presentation

![image](https://user-images.githubusercontent.com/61518251/77000804-50e84480-692f-11ea-8f6f-a0c2b48d8d32.png)

**Comment by BrendanGreenlee** [comment]
You may be able to do this by disabling the author-view (not called exactly that, but something like it). Shouldn't be a need to mess with CSS or other elements.

**Comment by CentralScrutinizer-moonbog** [comment]
Actually figured this out - adding the following code increases the page display:
classes: wide
