### ISSUE TITLE
Create Socialist Night School Page

### ISSUE THREAD

**Issue by BrendanGreenlee** [MetroDCDSA/MetroDCDSA.github.io#16]
Create page for socialist night school at /nightschool and link to the meetup / action network for individual events

**Comment by BrendanGreenlee** [comment]
Can we make it so the header/overlay image is the nightschool image you used for the event itself? This will help us with link previews.

**Comment by BrendanGreenlee** [comment]
Additionally, I took away the "Session One" part of the title since it wasn't formatted that way on the website. If we had collections for night school that contained each semester we should then put "session 1" etc. Call me if you have questions about this. 

Thank you for putting this together!

**Comment by CentralScrutinizer-moonbog** [comment]
updated page with new banner. COuldn't use the old one as it was new small, but new banner should work well
